package:
  name: vector
  version: "0.51.1"
  epoch: 0
  description: High-performance observability data pipeline
  copyright:
    - license: MPL-2.0
  resources:
    cpu: "22"
    memory: 36Gi
  test-resources:
    cpu: "1"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang
      - cmake
      - coreutils
      - libtool
      - llvm
      - make
      - openssl-dev
      - patch
      - perl
      - pkgconf
      - protobuf-dev
      - protoc
      - python3
      - rust-1.90

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vectordotdev/vector
      tag: v${{package.version}}
      expected-commit: 44c8f1cfd64bdedb924034c946f639d09890fc53
  - runs: |
      export CFLAGS="$CFLAGS -std=gnu17"
      cargo fetch --locked
      set -- "${CARGO_HOME:-$HOME/.cargo}"/registry/src/*/krb5-src-0.3.2+1.19.2
      [ "$#" -eq 1 ] && [ -d "$1" ]
      patch -d "$1" -p1 --fuzz=0 < krb5-c23-strchr.patch
      cargo auditable build --release --locked --no-default-features --features default-cmake
      install -m755 -D target/release/vector "${{targets.destdir}}/usr/bin/vector"
  - uses: strip

test:
  pipeline:
    - runs: /usr/bin/vector --version | grep -F "vector ${{package.version}}"
