name: grafana
track: wolfi
description: The open and composable observability and data visualization platform.
category: Monitoring & Observability
upstream: https://github.com/grafana/grafana
versions: [13.2]
owner: tektum
enabled: true
