package:
  name: rabbitmq-cluster-operator
  version: "2.22.3"
  epoch: 0
  description: RabbitMQ Cluster Operator for Kubernetes
  copyright:
    - license: MPL-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - go-1.26
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rabbitmq/cluster-operator
      tag: v${{package.version}}
      expected-commit: 03e0b49c077a9c8d926fb4c8cbe2dd0bbdffd539
  - runs: |
      go build -a -tags timetzdata -trimpath -ldflags="-s -w" -o manager ./cmd
      install -Dm755 manager "${{targets.destdir}}/usr/bin/manager"

test:
  pipeline:
    - runs: /usr/bin/manager --help
