contents:
  repositories:
    - https://packages.wolfi.dev/os
    - "@local @LOCAL_REPOSITORY@"
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - "@LOCAL_KEY@"
  packages:
    - ca-certificates-bundle
    - prometheus-operator@local

accounts:
  run-as: 65534

entrypoint:
  command: /bin/operator

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
