package:
  name: deno
  version: "2.9.6"
  epoch: 2
  description: A modern runtime for JavaScript and TypeScript.
  copyright:
    - license: MIT
  resources:
    cpu: "22"
    memory: 36Gi
  test-resources:
    cpu: "1"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang-${{vars.clang-version}}
      - cmake
      - glibc-dev
      - posix-libc-utils
      - protobuf-dev
      - protoc
      - python3
      - rust-1.95
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/denoland/deno
      tag: v${{package.version}}
      expected-commit: e518fbd66dda5debcbdefc0beb0b3756b37b64fa
  - uses: patch
    with:
      patches: rand-pin-bump.patch
  - runs: |
      cargo update -p rand@0.8.5 --precise 0.8.6
      cargo update -p quinn-proto --precise 0.11.17
  - uses: cargo/build
    with:
      output: deno
  - uses: strip

update:
  enabled: true
  github:
    identifier: denoland/deno
    strip-prefix: v

test:
  pipeline:
    - runs: deno --version

vars:
  clang-version: 22
