package:
  name: prometheus-alertmanager
  version: "0.34.0"
  epoch: 3
  description: Prometheus Alertmanager
  copyright:
    - license: Apache-2.0

vars:
  source-commit: 085f0ef7eb41da24cab8cd000f1345b6250f2edb

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - python3
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/alertmanager
      tag: v${{package.version}}
      expected-commit: ${{vars.source-commit}}
  - uses: fetch
    with:
      uri: >-
        https://github.com/prometheus/alertmanager/releases/download/v${{package.version}}/alertmanager-web-ui-${{package.version}}.tar.gz
      expected-sha256: 990d0be563b733bd0eae180dd609591164028f80cdf47ee8c1c3a1bfafff8d23
      directory: ui/app
      strip-components: 0
  - uses: go/remediate
    with:
      modroot: .
      packages: './cmd/alertmanager ./cmd/amtool'
  - runs: |
      flags="-s -w -X github.com/prometheus/common/version.Version=${{package.version}}"
      flags="$flags -X github.com/prometheus/common/version.Revision=${{vars.source-commit}}"
      go build -mod=readonly -trimpath -ldflags "$flags" -o alertmanager ./cmd/alertmanager
      go build -mod=readonly -trimpath -ldflags "$flags" -o amtool ./cmd/amtool
      install -m755 -D alertmanager "${{targets.destdir}}/usr/bin/alertmanager"
      install -m755 -D amtool "${{targets.destdir}}/usr/bin/amtool"

test:
  pipeline:
    - runs: /usr/bin/alertmanager --version
    - runs: /usr/bin/amtool --help
