package:
  name: verity-cluster-autoscaler-1.35
  version: "1.35.0"
  epoch: 0
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "6"
    memory: 12Gi
    disk: 8Gi

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: 25fc5c74f6b0f2382b65f76edc08e15ac9f41da7
  - uses: go/bump
    with:
      deps: |-
        github.com/google/cel-go@v0.29.0
        golang.org/x/crypto@v0.53.0
        golang.org/x/net@v0.56.0
        golang.org/x/text@v0.41.0
        google.golang.org/grpc@v1.82.1
      modroot: cluster-autoscaler
      tidy: false
  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      vendor: true

test:
  pipeline:
    - runs: /usr/bin/cluster-autoscaler --help
