package:
  name: verity-cluster-autoscaler-1.35
  version: "1.35.0"
  epoch: 1
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "6"
    memory: 12Gi
    disk: 8Gi

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - python3
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: 25fc5c74f6b0f2382b65f76edc08e15ac9f41da7
  - uses: go/remediate
    with:
      modroot: cluster-autoscaler
      packages: .
  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      vendor: true

test:
  pipeline:
    - runs: /usr/bin/cluster-autoscaler --help
