contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - helm-4=4.2.4-r0

accounts:
  run-as: 65532

entrypoint:
  command: /usr/bin/helm

environment:
  PATH: /usr/bin:/bin
